####################################################################################################
# Copyright (c) 2023 Bahman Movaqar
#
# This file is part of lemmy-meter.
# lemmy-meter is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# lemmy-meter is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with lemmy-meter.
# If not, see <https://www.gnu.org/licenses/>.
####################################################################################################

---
version: "3.8"
services:
  prometheus:
    image: "prom/prometheus:v2.55.1"
    command:
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=120d"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--log.level=debug"
    ports:
      - "9090:9090"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/prometheus:/etc/prometheus"
      - "prometheus-data:/prometheus"
    restart: always
  grafana:
    image: "grafana/grafana:10.4.19"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/grafana/grafana.ini:/etc/grafana/grafana.ini"
    ports:
      - "3000"
    deploy:
      replicas: 2
    user: "${UID}:${GID}"
    restart: always
  blackbox-exporter:
    image: "prom/blackbox-exporter:v0.26.0"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/blackbox-exporter/config.yml:/etc/blackbox_exporter/config.yml"
    ports:
      - "9115:9115"
    user: "${UID}:${GID}"
    restart: always
  json-exporter:
    image: "prometheuscommunity/json-exporter:v0.7.0"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/json-exporter/config.yml:/etc/json_exporter-config.yml"
    command:
      - "--config.file=/etc/json_exporter-config.yml"
    ports:
      - "7979:7979"
    user: "${UID}:${GID}"
    restart: always
  downtime-processor:
    image: "bahmanm/lemmy-meter.downtime-processor:df026af"
    entrypoint:
      - "perl"
    command:
      - "-I/opt/downtime-processor-lib/local/lib/perl5"
      - "downtime-processor.pl"
      - "prefork"
      - "-m"
      - "${LMDP_MODE}"
      - "-l"
      - "http://*:6060"
    ports:
      - "6060:6060"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/downtime-processor/:/opt/downtime-processor"
    working_dir: "/opt/downtime-processor"
    environment:
      - LMDP_JSON_SCHEMA=/opt/downtime-processor/scheduled-downtime-schema.json
      - LMDP_SCRAPE_TARGETS=/opt/downtime-processor/scrape-targets.txt
      - LMDP_LOG_LEVEL=${LMDP_LOG_LEVEL}
      - LMDP_GSHEET_URL=${LMDP_GSHEET_URL}
      - LMDP_GSHEET_HEADER_ROWS=${LMDP_GSHEET_HEADER_ROWS}
      - LMDP_NTFY_USERNAME=${LMDP_NTFY_USERNAME}
      - LMDP_NTFY_PASSWORD=${LMDP_NTFY_PASSWORD}
    user: "${UID}:${GID}"
    restart: always
  nginx:
    image: nginx:1.28
    ports:
      - "8000:80"
      - "8001:8001"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/nginx/static:/usr/share/nginx/html:ro"
      - "${CLUSTER_DEPLOY_ROOT}/nginx/conf.d/grafana.conf:/etc/nginx/conf.d/grafana.conf"
    restart: always
  postgres:
    image: postgres:16.9
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    restart: always
  alertmanager:
    image: prom/alertmanager:v0.28.1
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--log.level=debug"
    ports:
      - "9093:9093"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/alertmanager:/etc/alertmanager"
    restart: always
  smtp:
    image: ixdotai/smtp:v0.7.7
    ports:
      - "2525:25"
    environment:
      - GMAIL_USER=${SMTP_USER}
      - GMAIL_PASSWORD=${SMTP_PASSWORD}
  ntfy:
    image: binwiederhier/ntfy:v2.11.0
    entrypoint:
      - "/bin/sh"
      - "-c"
    command: >-
      "NTFY_PASSWORD=${LMDP_NTFY_PASSWORD} ntfy user add --ignore-exists ${LMDP_NTFY_USERNAME} && ntfy access ${LMDP_NTFY_USERNAME} '*' write-only && ntfy serve"
    environment:
      - TZ=UTC
    ports:
      - "8080:8080"
    volumes:
      - "${CLUSTER_DEPLOY_ROOT}/ntfy/server.yml:/etc/ntfy/server.yml"
      - "ntfy-var:/var/lib/ntfy"
      - "ntfy-cache:/var/cache/ntfy"
    restart: always
volumes:
  prometheus-data:
  postgres-data:
  ntfy-cache:
  ntfy-var:
networks:
  lemmy-meter:
    attachable: true
